# This is a basic workflow to help you get started with Actions

name: Deploy to Netlify

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest  # Usa una máquina virtual de Ubuntu para el proceso de despliegue

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Obtiene el código del repositorio

    - name: Install Netlify CLI
      run: npm install -g netlify-cli  # Instala Netlify CLI

    - name: Deploy to Netlify
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      run: |
        netlify deploy --prod --dir=./
