name: Versioning and Deployment Docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  version_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Configure Git
        run: |
          git config --global user.email "itsdata0@gmail.com"
          git config --global user.name "DataITS"

      - name: Stash local changes
        run: git stash --include-untracked

      - name: Pull latest changes from remote
        run: |
          git pull origin master || true
          git reset --hard origin/master

      - name: Apply stashed changes
        run: git stash pop || true

      - name: Resolve merge conflicts
        run: |
          git add package-lock.json
          git commit -m "Resolved merge conflicts"

      - name: Bump version and create tag
        run: |
          npm version patch
          git push origin master
          git push --tags

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          VERSION=$(npm pkg get version | tr -d '"')
          docker buildx build --platform linux/amd64 --tag usernetc/myapp:$VERSION --output type=docker .
          docker push usernetc/myapp:$VERSION
