name: Deploy with Rollback

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Asegurarnos de tener al menos dos commits en el historial

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the project
      - name: Build project
        run: npm run build

      - name: Deploy to Production
        id: deploy
        run: |
          echo "Deploying to production..."
          # Simula un fallo en el despliegue
          exit 1
        continue-on-error: true

      - name: Rollback if deployment failed
        if: failure()
        run: |
          echo "Deployment failed. Rolling back to the previous version..."
          # Solo rollback si hay al menos dos commits
          if [ "$(git rev-list --count HEAD)" -gt 1 ]; then
            git reset --hard HEAD^
            git push origin master --force
            echo "Rollback completed successfully"
          else
            echo "Not enough commits to roll back. Rollback not performed."
          fi
