name: Deploy with Rollback

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Asegurarnos de tener al menos dos commits en el historial

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the project
      - name: Build project
        run: npm run build

      # Deploy to Production (this will fail)
      - name: Deploy to Production
        id: deploy
        run: |
          echo "Deploying to production..."
          exit 1  # Forzamos un error para simular un despliegue fallido
        continue-on-error: true

      # Debug: Check deployment status
      - name: Debug:Check deployment status
        if: always()
        run: |
          if [ "${{ steps.deploy.outcome }}" == "failure" ]; then
            echo "Deployment failed. This should trigger rollback steps."
          else
            echo "Deployment succeeded. No rollback needed."
          fi

      # Rollback if deployment failed
      - name: Rollback if deployment failed
        if: always()
        run: |
          if [ "${{ steps.deploy.outcome }}" == "failure" ]; then
            echo "Deployment failed. Rolling back to the previous version..."
            if git rev-parse HEAD^ >/dev/null 2>&1; then
              git reset --hard HEAD^
              git push --force
              echo "Rollback completed successfully"
            else
              echo "No previous commit to roll back to. Rollback not performed."
            fi
          fi
